version: "3"
services:
  toxiproxy:
    image: "shopify/toxiproxy"
    ports:
      - "443:443" # port for example.com redirect
  client:
    build:
      context: .
    stdin_open: true
    tty: true
    depends_on:
      - configurator
    command: [/bin/bash]
  configurator:
    build: 
      context: .
      dockerfile: Dockerfile.configurator
    depends_on:
      - toxiproxy